Fruity_Veggies/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userAuth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),

    #! products view
    path('products', views.product_list_view, name="products"),
    path('product/<pid>', views.product_details_view, name="product"),

    #! category
    path('fruits', views.category_product_fruits_view, name="fruits"),
    path('vegetables', views.category_product_vegetables_view, name="vegetables"),

    #! vendor
    path('vendors', views.vendors_list_view, name="vendors"),
    path('vendor/<vid>', views.vendor_details_view, name="vendor"),

     #! tags
    path('products/tags/<slug:tag_slug>', views.tag_list_view, name="tags"),

    #! add reviews
    path('reviews/<pid>/', views.review_form_view, name="reviews"),

    #! Search by product title
    path('search/', views.search_products_view, name="search_products"),

    #! filter products by category, vendor
    path('filter_products/', views.filter_products_view, name="filter_products"),

    #! add product to cart
    path('add_to_cart', views.add_to_cart, name="add_to_cart"),

    #! cart page
    path('cart', views.cart_view, name="cart"),

    #! delete-item-from-cart
    path('delete-from-cart', views.delete_item_from_cart, name="delete-from-cart"),

    #! update cart
    path('update-cart', views.update_cart, name="update-cart"),

    #! Checkout url
    path('checkout', views.checkout_view, name="checkout"),

    #! paypal url
    path('paypal/', include('paypal.standard.ipn.urls')),

    #! payment completed url
    path('payment-completed', views.payment_completed_view, name="payment-completed"),

    #! payment failed url
    path('payment-failed', views.payment_failed_view, name="payment-failed"),

    #! dashboard url
    path('dashboard/', views.dashboard_view, name="dashboard"),

    #! order details url
    path('dashboard/order/<int:id>', views.order_detail_view, name="order-details"),

    #! making address default url
    path('make-default-address', views.make_address_default_view, name="make-default-address"),

    #! adding to wishlist url
    path('add-to-wishlist', views.add_to_wishlist_view, name="add-to-wishlist"),

    #! wishlist view url
    path('wishlist', views.wishlist_view, name="wishlist"),

    #! removing from wishlist view url
    path('remove-from-wishlist', views.remove_from_wishlist, name="remove-from-wishlist"),

    #! contact view url
    path('contact', views.contact_view, name="contact"),

    #! ajax contact view url
    path('ajax-contact-form', views.ajax_contact, name="ajax-contact-form"),
]

userAuth/urls.py
from django.urls import path

from . import views

app_name = 'userAuth'

urlpatterns = [
    path('register', views.register_view, name="register"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
]

core/forms.py
from django import forms

from . models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write a review'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.http import JsonResponse
from django.core import serializers

from django.contrib.auth.decorators import login_required

from django.template.loader import render_to_string

from . models import Product, Category, Vendor, ProductImages, CartOrder, CartOrderItems, ProductReview, WishList, Address
from userAuth.models import ContactUs

from . forms import ProductReviewForm

from taggit.models import Tag

from django.contrib import messages #! for flash messages

from django.db.models import Avg, Count

#! for paypal
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
# Create your views here.

def index(request):

    products = Product.objects.filter(product_status = "published", featured = True)
    category_v = Category.objects.filter(title = "Vegetables")
    vegetables = Product.objects.filter(category__title = "Vegetables")
    fruits = Product.objects.filter(category__title = "Fruits")
    categories = Category.objects.all()

    context = {
        'products': products, 'categories': categories, 'vegetables': vegetables, 'fruits': fruits
    }
    return  render(request, 'core/index.html', context)

def product_list_view(request):

    products = Product.objects.filter(product_status = "published", featured=True)
    vegetables = Product.objects.filter(category__title = "Vegetables")
    fruits = Product.objects.filter(category__title = "Fruits")

    context = {
        'products': products, 'vegetables': vegetables, 'fruits': fruits
    }
    return render(request, 'core/product_list.html', context)

def product_details_view(request, pid):

    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid) #![:4] at the end to show first 4

    vegetables = Product.objects.filter(category__title = "Vegetables")
    fruits = Product.objects.filter(category__title = "Fruits")
    #!get all reviews
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    #! getting average reviews
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    #! product review form
    review_form = ProductReviewForm()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False
    
    

    context = {
        'product': product, 'products':products ,'fruits': fruits, 'vegetables': vegetables,
        'reviews': reviews, 'average_rating': average_rating, 'review_form': review_form,
        'make_review': make_review
    }

    return render(request, 'core/product_details.html', context)

def category_product_fruits_view(request):

    fruits = Product.objects.filter(category__title = "Fruits")

    context = {'fruits': fruits}
    return render(request, 'core/category_fruits_list.html', context)

def category_product_vegetables_view(request):

    vegetables = Product.objects.filter(category__title = "Vegetables")

    context = {'vegetables': vegetables}
    return render(request, 'core/category_vegetables_list.html', context)

def vendors_list_view(request):

    vendors = Vendor.objects.all()

    context = {
        'vendors': vendors
    }
    return render(request, 'core/vendors_list.html', context)

def vendor_details_view(request, vid):

    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status = "published")

    context = {
        'vendor': vendor, 'products': products
    }
    return render(request, 'core/vendor_details.html', context)

def tag_list_view(request, tag_slug=None):

    products = Product.objects.filter(product_status = "published")
    vegetables = Product.objects.filter(category__title = "Vegetables")
    fruits = Product.objects.filter(category__title = "Fruits")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        'products': products, 'tag': tag, 'vegetables': vegetables, 'fruits': fruits
    }

    return render(request, 'core/tag.html', context)

def review_form_view(request, pid):
    
    product = Product.objects.get(pid=pid)
    user = request.user

    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST.get('review'),
        rating = request.POST.get('rating'),
    )

    context = {
        'user': user.username,
        'review': request.POST.get('review'),
        'rating': request.POST.get('rating'),
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    return JsonResponse(
        {
            'bool': True,
            'context': context,
            'average_reviews': average_reviews,
        }
    )

def search_products_view(request):

    query = request.GET.get("q")
    products = Product.objects.filter(title__icontains=query, product_status = "published")
    vegetables = Product.objects.filter(category__title = "Vegetables")
    fruits = Product.objects.filter(category__title = "Fruits")

    #? products = Product.objects.filter(title__icontains=query, description__icontains=query).order_by("-date")

    context = {
        'products': products,
        'query': query, 'vegetables': vegetables, 'fruits': fruits
    }
    return render(request, 'core/search_products.html', context)

def filter_products_view(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").distinct()

    products = products.filter(price__gte=min_price) #! product is greater than or equal to min_price
    products = products.filter(price__lte=max_price) #! product is less than or equal to max price

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    data = render_to_string("core/async/products_list.html", {'products': products})

    return JsonResponse({'data': data})

#!Add to cart
def add_to_cart(request):

    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'quantity': request.GET['quantity'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],
    }

    #! we will be using 'cart_data_obj' as a session. This is how we create the session.
    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj'] #! get that object
            cart_data[str(request.GET['id'])]['quantity'] = int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse({
        'data': request.session['cart_data_obj'],
        'total_cart_items': len(request.session['cart_data_obj'])
    })

#! cart view
def cart_view(request):

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])
        return render(request, 'core/cart.html', {'cart_data': request.session['cart_data_obj'], 'total_cart_items': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
    else:
        messages.warning(request, 'Your cart is empty')
        return redirect('core:index')
#! delete item from cart
def delete_item_from_cart(request):

    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])

    data = render_to_string("core/async/cart-list.html", {'cart_data': request.session['cart_data_obj'], 'total_cart_items': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})

    return JsonResponse({"data": data, "total_cart_items": len(request.session['cart_data_obj'])})

#! update cart items
def update_cart(request):

    product_id = str(request.GET['id'])
    product_quantity = request.GET['quantity']
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['quantity'] = product_quantity
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])

templates/core/cart.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

    <main id="cart-list">
        <!-- Single Page Header start -->
        <div class="container-fluid page-header py-5">
            <h1 class="text-center text-white display-6">Cart</h1>
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'core:products' %}">Products</a></li>
                <li class="breadcrumb-item active text-white">You have {{total_cart_items}} Cart items</li>
            </ol>
        </div>
        <!-- Single Page Header End -->


        <!-- Cart Page Start -->
        <div class="container-fluid py-5">
            <div class="container py-5">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Products</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                            <th scope="col">Refresh</th>
                            <th scope="col">Remove</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for p_id, item in cart_data.items %}
                            <tr>
                                <th scope="row">
                                    <div class="d-flex align-items-center">
                                        <a href="{% url 'core:product' item.pid %}">
                                            <img src="{{item.image}}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                        </a>                      
                                    </div>
                                </th>
                                <td>
                                    <p class="mb-0 mt-4"><a href="{% url 'core:product' item.pid %}">{{item.title}}</a></p>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">$ <span>{{item.price|floatformat:2}}</span></p>
                                </td>
                                <td>
                                    <div class="input-group quantity mt-4" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <button class="btn btn-sm btn-minus rounded-circle bg-light border" >
                                            <i class="fa fa-minus"></i>
                                            </button>
                                        </div>
                                        <input type="number" class=" product-quantity-{{ p_id }} form-control form-control-sm text-center border-0" value="{{item.quantity}}">
                                        <div class="input-group-btn">
                                            <button class="btn btn-sm btn-plus rounded-circle bg-light border">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">$ {% widthratio item.price 1 item.quantity %}</p>
                                </td>
                                <td>
                                    <button class=" update-product btn btn-md rounded-circle bg-light border mt-4" data-product="{{p_id}}" >
                                        <i class="fa fa-correct text-danger"></i>
                                    </button>
                                </td>
                                <td>
                                    <button class=" delete-product btn btn-md rounded-circle bg-light border mt-4" data-product="{{p_id}}">
                                        <i class="fa fa-times text-danger"></i>
                                    </button>
                                </td>
                            
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="mt-5">
                    <input type="text" class="border-0 border-bottom rounded me-5 py-3 mb-4" placeholder="Coupon Code">
                    <button class="btn border-secondary rounded-pill px-4 py-3 text-primary" type="button">Apply Coupon</button>
                </div>
                <div class="row g-4 justify-content-end">
                    <div class="col-8"></div>
                    <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
                        <div class="bg-light rounded">
                            <div class="p-4">
                                <h1 class="display-6 mb-4">Cart <span class="fw-normal">Total</span></h1>
                                <!-- <div class="d-flex justify-content-between mb-4">
                                    <h5 class="mb-0 me-4">Subtotal:</h5>
                                    <p class="mb-0">$96.00</p>
                                </div> -->
                                <!-- <div class="d-flex justify-content-between">
                                    <h5 class="mb-0 me-4">Shipping</h5>
                                    <div class="">
                                        <p class="mb-0">Flat rate: $3.00</p>
                                    </div>
                                </div>
                                <p class="mb-0 text-end">Shipping to Ukraine.</p> -->
                            </div>
                            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                                <h5 class="mb-0 ps-4 me-4">Total</h5>
                                <p class="mb-0 pe-4">${{cart_total_amount|floatformat:2}}</p>
                            </div>
                            {% if total_cart_items %}
                            <a href="{% url 'core:checkout' %}" class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4">Proceed Checkout</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
        <!-- Cart Page End -->

{% endblock content %}

templates/core/checkout.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}


        <!-- Single Page Header start -->
        <div class="container-fluid page-header py-5">
            <h1 class="text-center text-white display-6">Checkout</h1>
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'core:cart' %}">Cart</a></li>
                <li class="breadcrumb-item active text-white">You have {{total_cart_items}} items in Checkout</li>
            </ol>
        </div>
        <!-- Single Page Header End -->


        <!-- Checkout Page Start -->
        <div class="container-fluid py-5">
            <div class="container py-5">
                <h1 class="mb-4">Billing Address</h1>
                {{active_address.id}}
                    <div class="row g-5">
                        
                        <div class="col-md-12 col-lg-6 col-xl-7">
                            <div class="row">
                                <div class="col-md-12 col-lg-6">
                                    <div class=" w-100">
                                        <label class="f my-3">Name</label>
                                        <input type="text" value="{{request.user|title}}" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-12 col-lg-6">
                                    <div class=" w-100">
                                        <label class="f my-3">Phone</label>
                                        <input type="text" value="{{a.mobile}}" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="">
                                <label class=" my-3">Address</label>
                                <input type="text" value="{{a.address}}" class="form-control">
                            </div>
                        </div>

                        <div class="col-md-12 col-lg-6 col-xl-5">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">Products</th>
                                            <th scope="col">Name</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Quantity</th>
                                            <th scope="col">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for p_id, item in cart_data.items %}
                                        <tr>
                                            <th scope="row">
                                                <div class="d-flex align-items-center mt-2">
                                                    <a href="{% url 'core:product' item.pid %}">
                                                        <img src="{{item.image}}" class="img-fluid rounded-circle" style="width: 90px; height: 90px;" alt="">
                                                    </a>
                                                    
                                                </div>
                                            </th>
                                            <td class="py-5"> <a href="{% url 'core:product' item.pid %}">{{item.title}}</a> </td>
                                            <td class="py-5">${{item.price}}</td>
                                            <td class="py-5">{{item.quantity}}</td>
                                            <td class="py-5">${% widthratio item.price 1 item.quantity %}</td>
                                        </tr>
                                        {% endfor %}
                                            <th scope="row">
                                            </th>
                                            <td class="py-5">
                                                <p class="mb-0 text-dark text-uppercase py-3">TOTAL</p>
                                            </td>
                                            <td class="py-5"></td>
                                            <td class="py-5"></td>
                                            <td class="py-5">
                                                <div class="py-3 border-bottom border-top">
                                                    <p class="mb-0 text-primary">${{cart_total_amount|floatformat:2}}</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="row g-4 text-center align-items-center justify-content-center pt-4">
                                {{paypal_payment_button.render}}
                            </div>  
                        </div>
                    </div>
                
                
            </div>
        </div>
        <!-- Checkout Page End -->


{% endblock content %}

templates/core/wishlist.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

    <main id="wishlist-list">
        <!-- Single Page Header start -->
        <div class="container-fluid page-header py-5">
            <h1 class="text-center text-white display-6">Wishlist</h1>
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'core:products' %}">Products</a></li>
                <li class="breadcrumb-item active text-white">You have {{wishlist.count}} items in Wishlist</li>
            </ol>
        </div>
        <!-- Single Page Header End -->


        <!-- Cart Page Start -->
        <div class="container-fluid py-5">
            <div class="container py-5">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Products</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Stock Status</th>
                            <th scope="col">Action</th>
                            <th scope="col">Remove</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for w in wishlist %}
                            <tr>
                                <th scope="row">
                                    <div class="d-flex align-items-center">
                                        <a href="{% url 'core:product' w.product.pid %}">
                                            <img src="{{w.product.image.url}}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                        </a>                      
                                    </div>
                                </th>
                                <td>
                                    <p class="mb-0 mt-4"><a href="{% url 'core:product' w.product.pid %}">{{w.product.title}}</a></p>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4" >$ <span class="current-product-price-{{w.product.id}}">
                                        {{w.product.price|floatformat:2}}
                                    </span>
                                </p>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">{% if w.product.in_stock %} <span class="text-primary">In Stock</span> {% else %} <span class="text-danger">Out of Stock</span>  {% endif %}</p>
                                </td>
                                <td>
                                    <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{w.product.id}}" >
                                    <input type="hidden" class="product-pid-{{w.product.id}}" value="{{w.product.pid}}">
                                    <input type="hidden" class="product-image-{{w.product.id}}" value="{{w.product.image.url}}">
                                    <input type="hidden" class="product-id-{{w.product.id}}" value="{{w.product.id}}">
                                    <input type="hidden" class="product-title-{{w.product.id}}" value="{{w.product.title}}">
                                    <button id="add-to-cart-btn" data-index="{{w.product.id}}" class="add-to-cart-btn btn border border-secondary rounded-pill px-3 mt-4 text-primary">
                                        <i class="fa fa-shopping-bag me-2 text-primary"></i> 
                                        Add to cart
                                    </button>
                                </td>
                                <td>
                                    <button class=" delete-wishlist-product btn btn-md rounded-circle bg-light border mt-4" data-wishlist-product="{{w.id}}"">
                                        <i class="fa fa-trash text-danger"></i>
                                    </button>
                                </td>
                            
                            </tr>
                            {% empty %}
                            <tr>
                                <td><p class="mb-0 mt-4">No Item in wishlist. Add a product to the wishlist to view it.</p></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}